version: '3'

services:
  db:
    image: postgres:12.8
    container_name: postgres-db
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
